spring.application.name=gateway
server.port=8090

auth.service.url=${AUTH_SERVICE_URL:http://localhost:8080}
message.service.url=${MESSAGE_SERVICE_URL:http://localhost:8081}
media.service.url=${MEDIA_SERVICE_URL:http://localhost:8082}
presence.service.url=${PRESENCE_SERVICE_URL:http://localhost:8083}
frontend.url=${FRONTEND_URL:http://localhost:5173}
