spring.application.name=media
server.port=8082
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5435/${POSTGRES_DB3}
spring.datasource.username=${POSTGRES_MEDIA}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
